name: Test Crowdin integration

on:
  push:
    branches:
      - 'crowdin/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:17-alpine
    env:
      CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
      CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
      # Required for npm to install the java package used by crowdin CLI
      JAVA_HOME: "/usr/lib/jvm/java-11-openjdk/"
    steps:
    - name: "Install deps"
      run: |
        apk add python3 py3-pip make g++ git openjdk11 bash

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install J2
      run: |
        pip install j2cli

    - name: Set env
      run: |
        # Gets repository name (without owner prefix) variable
        echo "PROJECT_NAME=$(echo ${GITHUB_REPOSITORY} | cut -d "/" -f2)" >> $GITHUB_ENV
        echo "PATH=$(echo "$PATH:/usr/lib/jvm/java-11-openjdk/jre/bin")" >> $GITHUB_ENV

    - name: Generate docusaurus.config.js.j2
      run: |
        j2 docusaurus.config.js -o docusaurus.config.js
        cat docusaurus.config.js

    - name: "yarn deps"
      run: |
        yarn

    - name: "Docusaurus write-translations"
      run: |
        yarn write-translations

    - name: "Crowdin upload"
      run: yarn crowdin-upload

    - name: "Crowdin download"
      run: yarn crowdin-download

    - name: "yarn deploy"
      env:
        DEPLOYMENT_BRANCH: "gh-pages-crowdin"
        NODE_OPTIONS: --openssl-legacy-provider
      run: |
        git config --global user.name 'ChiaAutomation'
        git config --global user.email 'automation@chia.net'
        GIT_USER=ChiaAutomation GIT_PASS=${{ github.token }} yarn deploy
