name: Build pages non trunk

on:
  push:
    branches:
      - "*"
      - "!main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:17-alpine
    steps:
    - name: "Install deps"
      run: |
        apk add python3 make g++ git

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: "yarn deps"
      run: |
        yarn

    - name: "yarn build"
      run: |
        yarn build

    - uses: actions/upload-artifact@v2
      with:
        name: pages-rendering
        path: ./
