name: Deploy to pages on trunk

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  docusaurus-translations:
    runs-on: ubuntu-latest
    container: node:17-alpine
    steps:
    - name: "Install deps"
      run: |
        apk add python3 py3-pip make g++ git openjdk11

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: "yarn deps"
      run: |
        yarn

    - name: "docusaurus write-translations"
      run: |
        yarn write-translations

  crowdin:
    runs-on: ubuntu-latest
    container: openjdk:11
    needs: [docusaurus-translations]
    env:
      CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
      CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: "Install crowdin CLI"
      run: |
        wget -qO - https://artifacts.crowdin.com/repo/GPG-KEY-crowdin | apt-key add -
        echo "deb https://artifacts.crowdin.com/repo/deb/ /" > /etc/apt/sources.list.d/crowdin.list
        apt update && apt install crowdin3

    - name: "Crowdin upload"
      run: crowdin upload"

    - name: "Crowdin download"
      run: crowdin download"

  deploy:
    runs-on: ubuntu-latest
    container: node:17-alpine
    needs: [docusaurus-translations,crowdin]
    steps:
    - name: "Install deps"
      run: |
        apk add python3 py3-pip make g++ git openjdk11

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install J2
      run: |
        pip install j2cli

    - name: Set env
      run: |
        # Gets repository name (without owner prefix) variable
        echo "REPOSITORY_NAME=$(echo ${GITHUB_REPOSITORY} | cut -d "/" -f2)" >> $GITHUB_ENV

    - name: Generate docusaurus.config.js.j2
      run: |
        j2 docusaurus.config.js.j2 -o docusaurus.config.js
        cat docusaurus.config.js

    - name: "yarn deps"
      run: |
        yarn

    - name: "yarn deploy"
      run: |
        git config --global user.name 'ChiaAutomation'
        git config --global user.email 'automation@chia.net'
        GIT_USER=ChiaAutomation GIT_PASS=${{ github.token }} yarn deploy
