name: Deploy to pages on trunk

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:17
    steps:
    - name: "Install deps"
      run: |
        apt update
        apt install python3 make g++ git openssl

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: "yarn deps"
      run: |
        yarn

    - name: "yarn deploy"
      run: |
        git config --global user.name 'ChiaAutomation'
        git config --global user.email 'automation@chia.net'
        GIT_USER=ChiaAutomation GIT_PASS=${{ github.token }} yarn deploy
