name: Deploy Review App on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read
  packages: write

concurrency:
  group: ${{ github.event.pull_request.number }}

jobs:
  package:
    uses: Chia-Network/actions/.github/workflows/docker-build.yaml@main

  deploy:
    name: Deploy
    needs:
      - package
    runs-on: [k8s-public]
    container:
      image: registry.gitlab.com/cmmarslender/kubectl-helm:v3.11.0
    environment:
      name: Review ${{ github.event.pull_request.number }}
      url: https://${{ github.event.pull_request.number }}-docs.chia.net
    steps:
      - uses: actions/checkout@v3

      - name: Vault Login
        uses: Chia-Network/actions/vault/login@main
        with:
          vault_url: ${{ secrets.VAULT_URL }}
          role_name: github-chia-docs

      - name: Get ephemeral aws credentials
        uses: Chia-Network/actions/vault/aws-sts@main
        with:
          vault_url: ${{ secrets.VAULT_URL }}
          vault_token: ${{ env.VAULT_TOKEN }}
          role_name: pub-metrics-deploy

      - name: Log in to cluster
        run: aws eks update-kubeconfig --name pub-metrics --region us-west-2

      - uses: Chia-Network/actions/helm/deploy@main
        env:
          DOCKER_TAG: "sha-${{ github.sha }}"
          REVIEW_SLUG: ${{ github.event.pull_request.number }}
        with:
          namespace: "chia-docs"
          app_name: "chia-docs-${{ env.REVIEW_SLUG }}"
          helm_chart_repo: "https://chia-network.github.io/helm-charts"
          helm_chart: "generic"
          helm_values: "./k8s/review.yaml"
